# Site settings
title: iOS ML | A simple iOS Machine Learning Blog
description: "Understand all consequences of discovering AI and help lots of people with that"
url: "http://www.jacoporabolini.com/emerald"
author:
  name: "Alan Rabelo Martins"
  email: "alanrabelo@icloud.com"
  url: "http://www.jacoporabolini.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

theme: jekyll-theme-midnight